Issue #10, create menu class
NextPP/sudoManager pull request #13
Opened 2023-04-10 16:14 UTC by Chaitanya8135

adds Menu class as per #10 , assuming interface of Item class as in #6.

2023-04-11 14:05 UTC, RockyDesigne requested changes
Lacks error handling.

2023-04-11 14:05 UTC, RockyDesigne commented on src/Menu.cpp
> +        return -1.0;
should throw an error instead.

2023-04-11 19:16 UTC, Chaitanya8135 commented on src/Menu.cpp
> +}
Apologies, the `find_item` function was not meant to be exposed, it's now made private (can only be called within the class).
The exception mentioned is handled by the functions that call `find_item`.

2023-04-12 15:19 UTC, genciberisha requested changes
Thank you for your contribution!
I have updated the base **cmake** system of the project, please pull from main
and resolve conflicts.

2023-04-12 15:19 UTC, genciberisha commented on include/sudoManager/Menu.hpp
> +#include "Item.hpp"
```suggestion
#include "sudoManager/Item.hpp"
```

2023-04-12 15:19 UTC, genciberisha commented on src/Menu.cpp
> +#include "Item.cpp"
```suggestion
#include "sudoManager/Item.hpp"
```

2023-04-13 00:18 UTC, genciberisha commented
Pull from **main** before resolving the issues

2023-04-14 15:54 UTC, closed without merging